# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: monparcours

networks:
  postgres-habitat-souscription-nt:

services:
  postgres-habitat-souscription:
    container_name: "postgres-habitat-souscription"
    image: postgres:16.3
    environment:
      - POSTGRES_USER=MonParcours
      - POSTGRES_PASSWORD=MonParcours
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data
    networks:
      - postgres-habitat-souscription-nt
    volumes:
      - db-habitat-souscription-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    restart: always

  pgadmin-habitat-souscription:
    container_name: "pgadmin-habitat-souscription"
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 127.0.0.1:8080:80
    networks:
      - postgres-habitat-souscription-nt
    volumes:
      - pgadmin-habitat-souscription-data:/root/.pgadmin
    #  On s'assure que PgAdmin démarre après PostgreSQL.
    depends_on:
      - postgres-habitat-souscription
    restart: always

volumes:
  db-habitat-souscription-data:
  pgadmin-habitat-souscription-data:

