{{- $release_name := (include "common-library.fullname" .) -}}
  {{- $custom := .Values.custom | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $release_name }}--certs
  labels:
    {{- include "common-library.metadata.labels" . | nindent 4 }}
data:
  app-keystore.p12:
{{- if hasKey $custom "appKeystore" }}
{{- $custom.appKeystore | b64enc | indent 1 }}
{{- else }}
{{- "" }}
{{- end }}
  apim-keystore.p12:
{{- if hasKey $custom "apimKeystore" }}
{{- $custom.apimKeystore | b64enc | indent 1 }}
{{- else }}
{{- "" }}
{{- end }}
  kafka-keystore.jks:
{{- if hasKey $custom "kafkaKeystore" }}
{{- $custom.kafkaKeystore | b64enc | indent 1 }}
{{- else }}
{{- "" }}
{{- end }}
 kafka-truststore.jks:
{{- if hasKey $custom "kafkaTruststore" }}
{{- $custom.kafkaTruststore | b64enc | indent 1 }}
{{- else }}
{{- "" }}
{{- end }}
